import Layout from '@components/Layout'
import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>MoDo Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Layout>


      <main className='min-h-screen, p-16 flex-1 flex flex-col justify-center items-center'>
        <h1 className='text-modo-negro no-underline leading-5 m-0 text-6xl text-center dark:text-white'>
          Bienvenido a <a className= 'hover:text-neutral-200 dark:hover:text-neutral-200 text-rose-500 active:bg-violet-700 focus:outline-none focus:ring focus:ring-violet-300 ' href="https://modoccs.com">MoDo </a> Link!
        </h1>

        <p className='text-black dark:text-white m-16 text-2xl'>
          Elija una empresa{' '}
{/*           <code className='bg-slate-50 p-1 rounded-md text-lg '>pages/index.js</code> */}
        </p>

        <div className='max-w-fit flex-col-2 flex items-center content-center flex-wrap '>\

        <Link href="/conceptStore" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-black text-black dark:hover:bg-white dark:hover:text-black dark:text-white font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent rounded m-9">Concept Store &rarr;</button>
          </Link>

          <Link href="/salumeriaChacao" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-black text-black dark:hover:bg-white dark:hover:text-black dark:text-white font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent rounded m-9">Salumeria Chacao &rarr;</button>
          </Link>

          <Link href="/salumeriaHatillo" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-black text-black dark:hover:bg-white dark:hover:text-black dark:text-white font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent rounded m-9">Salumeria Hatillo &rarr;</button>
          </Link>

          <Link href="/modoExpress" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-black text-black dark:hover:bg-white dark:hover:text-black dark:text-white font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent rounded m-9">MoDo Delivery &rarr;</button>
          </Link>

          <Link href="/modo" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>

          <button className="bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent rounded m-9">MoDo &rarr;</button>
          </Link>

        </div>
      </main>
</Layout>
</>
  )
}
