import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useLinks} from '../context/LinkContext'
import {useTheme} from 'next-themes'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function Home() {
  const {link, setLink}= useLinks()
  const {theme, setTheme} = useTheme()
  return (
    <div className={styles.container}>
      <Head>
        <title>MoDo Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className='min-h-screen, p-12 flex-1 flex flex-col justify-center items-center'>
        <h1 className={styles.title}>
          Bienvenido a <a href="https://modoccs.com">MoDo </a> Link!
        </h1>

        <p className={styles.description}>
          Elija una empresa{' '}
{/*           <code className='bg-slate-50 p-1 rounded-md text-lg '>pages/index.js</code> */}
        </p>

        <div className='max-w-fit flex-col-2 flex items-center content-center flex-wrap '>\

        <Link href="/conceptStore" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded m-9">Concept Store &rarr;</button>
          </Link>

          <Link href="/salumeriaChacao" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded m-9">Salumeria Chacao &rarr;</button>
          </Link>

          <Link href="/salumeriaHatillo" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded m-9">Salumeria Hatillo &rarr;</button>
          </Link>

          <Link href="/modoExpress" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded m-9">MoDo Delivery &rarr;</button>
          </Link>

          <Link href="/modo" className='m-3 p-4 text-left text-inherit no-underline border-solid border border-gray-800 rounded-lg transition-colors delay-50 hover:text-indigo-600  hover:border-indigo-600 duration-100 max-w-xs'>
          <button className="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded m-9">MoDo &rarr;</button>
           {/*  <h2 className='mb-4 text-2xl text-dark dark:text-white'></h2> */}

{/*             {console.log(`link de index ${link}`)} */}
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div className='flex items-center justify-center'>

            Powered by{' '}
            <span className='invert-0 h-8 ml-2 dark:invert'>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </div>
        </Link>
      </footer>
    </div>
  )
}
