import Head from 'next/head'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>MoDo Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className='grid gap-10 text-modo-negro no-underline mt-10 pb-10
         leading-5 m-0 text-6xl text-center dark:text-white'>
          Bienvenido a <Link className= 'text-black dark:text-white hover:text-neutral-200 dark:hover:text-neutral-200' href="https://www.modoccs.com/main" target="_blank" rel="noreferrer" >MoDo </Link> Link!
        </h1>
      <main className='min-h-fit pt-10 flex-1 flex flex-col justify-center items-center'>

        <p className='text-black dark:text-white mb-1 text-2xl'>
          Elija una empresa{' '}

        </p>

        <div className=' md:grid md:grid-cols grid-cols-4 items-center content-center flex-wrap '>

        <Link href='/modo' className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded'>
           <button>MoDo</button>
        </Link>

        <Link href="/conceptStore" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
              <button >Concept Store</button>
          </Link>
          <Link href="/salumeriaChacao" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
          <button >Salumeria Chacao</button>
          </Link>
          <Link href="/modoExpress" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
          <button >Produccion Piquin</button>
          </Link>
          <Link href="/modoCandelaria" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
          <button>MoDo Candelaria</button>
          </Link>
          <Link href="/modoGlpi" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
          <button >MoDo GLPI</button>
          </Link>
          <Link href="/modoSanLuis" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
            <button >MoDo San Luis</button>
          </Link>
          <Link href="/modoAulaVirtual" className='flex items-center justify-center bg-transparent hover:bg-black text-black dark:text-white dark:hover:bg-white dark:hover:text-black font-semibold hover:text-white p-3 m-3 border dark:border-white border-black hover:border-transparent rounded max-w-xs'>
            <button >MoDo Aula Virtual</button>
          </Link>



        </div>
      </main>
</>
  )
}
